### ISSUE TITLE
Would the boost(1_73_0)::mpi::all_gatherv() result in memory leakage?

### ISSUE THREAD

**Issue by BinPeng-usst** [boostorg/mpi#123]
Hi,

I got an issue in my C++ codes.
I tried to gather information as follows,
"......
std::vector<CPdPoint *> * m_pPdPointList;
 std::vector<CPdPoint *> * s_pPdPointList;
.......
 boost::mpi::all_gatherv < CPdPoint * >(CWorld, *s_pPdPointList, *m_pPdPointList, m_iSendNum);
......."
The gathering WORKS but the MEMORY used by the program kept INCREASING.

I have tried to replace the pointers  and changed to 
"......
std::vector< CPdPoint >  m_P;
 std::vector< CPdPoint >  s_P;
.......
 boost::mpi::all_gatherv < CPdPoint > (CWorld, s_P, m_P, m_iSendNum);
......."

For the change, the gathering doesn't WORK and errors threw out as follows,
"......
[0] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error -1, comm rank 0
[1-2] terminated
......"

Any help or discussion is greatly appreciated.

Peng

**Comment by aminiussi** [comment]
Hi,

First, I'm not sure what the first example is trying to do. Communicating pointer fro one address space to another cannot work.

Do you have a complete self contained test case I can try ?

Thanks

**Comment by BinPeng-usst** [comment]
Aminiussi,

Thank you very much for your attention.

Sorry i can't make a self contained test because the part relates to too many other data structures.
I would like to explain as follows,

In the first example, the **CPdPoint** is a complicated class and I have made it serializable.
There are many CPdPoint objects. The pointer vector **m_pPdPointList** contains all the pointers to them and each vector **s_pPdPointList** contains a part of the pointers. 
I am trying to gather all the **s_pPdPointLists** in to a **m_pPdPointList**.

The example does WORK and i have verified its results. The ONLY ISSUE is that the memory it used keeps increasing. 

I doubt there could be something wrong with the pointers, too.
Therefore, i replaced all the pointers, i. e., using **std::vector< CPdPoint >** to replace **std::vector< CPdPoint *>** without changing any other parts of the program. 
However, the program fails after the change.

Hope i have made it clear :-)

Thanks again.

Peng

**Comment by aminiussi** [comment]
Well, if that works:
```
"......
std::vector<CPdPoint *> * m_pPdPointList;
std::vector<CPdPoint *> * s_pPdPointList;
.......
boost::mpi::all_gatherv < CPdPoint * >(CWorld, *s_pPdPointList, *m_pPdPointList, m_iSendNum);
......."
The gathering WORKS but the MEMORY used by the program kept INCREASING.
```
it's probably for wrong reasons, the address of a point in one process can hardly have a meaning in another one.

As for the later, there is not much that can be said without a self contained example. I've never encountered  such a problem before and Boost.MPI memory management is mostly automatic.

You can try a valgrind run to track down that issue.

Cheers

**Comment by BinPeng-usst** [comment]
Alain ，

Thank you so much.
Your are right.  The issue roots in the improper using of pointers.
I just replace all the pointers and it works properly now.

Best regards

Peng

**Comment by BinPeng-usst** [comment]
Alain ，

 

Thank you so much.

You are right.  The issue roots in the improper using of pointers.

I just replace all the pointers and it works properly now.

 

Best regards

 

Peng

 

发件人: noreply@github.com <noreply@github.com> 代表 Alain Miniussi
发送时间: 2020年8月7日 3:23
收件人: boostorg/mpi <mpi@noreply.github.com>
抄送: Bin Peng <BinPeng@usst.edu.cn>; Author <author@noreply.github.com>
主题: Re: [boostorg/mpi] Would the boost(1_73_0)::mpi::all_gatherv() result in memory leakage? (#123)

 

Well, if that works:

"......
std::vector<CPdPoint *> * m_pPdPointList;
std::vector<CPdPoint *> * s_pPdPointList;
.......
boost::mpi::all_gatherv < CPdPoint * >(CWorld, *s_pPdPointList, *m_pPdPointList, m_iSendNum);
......."
The gathering WORKS but the MEMORY used by the program kept INCREASING.

it's probably for wrong reasons, the address of a point in one process can hardly have a meaning in another one.

As for the later, there is not much that can be said without a self contained example. I've never encountered such a problem before and Boost.MPI memory management is mostly automatic.

You can try a valgrind run to track down that issue.

Cheers
