### ISSUE TITLE
Missing all_gatherv declaration in collectives.hpp

### ISSUE THREAD

**Issue by stubbsda** [boostorg/mpi#131]
The header file collectives.hpp doesn't contain any declarations for the all_gatherv functions (introduced in version 1.67), so that any use of boost::mpi::all_gatherv has to explicitly load the relevant header file,
#include <boost/mpi/collectives/all_gatherv.hpp>
Would it be possible to include the declaration of all_gatherv functions in collectives.hpp so that a single 
#include <boost/mpi.hpp>
suffices for software using all_gatherv?

**Comment by aminiussi** [comment]
Just merged in develop
