### ISSUE TITLE
Boost.Python no longer has separate targets for python 2 / 3

### ISSUE THREAD

**Issue by sdebionne** [boostorg/mpi#64]
The symptoms are:

```
error: Unable to find file or target named
error:     '/boost/python//boost_python3'
error: referred to from project at
error:     'libs/mpi/build'
```

And indeed `boost_python3` does not exist anymore in the [Jamfile](https://github.com/boostorg/python/blob/develop/build/Jamfile)

I'll try to do a PR to fix that. I am not sure why this passed the tests though.

**Comment by aminiussi** [comment]
Hi, 

I think this was fixed with https://github.com/boostorg/mpi/pull/65

Thanks
