### ISSUE TITLE
communicator::sendrecv is not shown in the documentation

### ISSUE THREAD

**Issue by bellaz89** [boostorg/mpi#85]
Even if an implementation of sendrecv is present in boost::mpi::communicator

https://github.com/boostorg/mpi/blob/develop/include/boost/mpi/communicator.hpp#L511-L541
https://github.com/boostorg/mpi/blob/develop/include/boost/mpi/communicator.hpp#L1532-L1539

The support in the documentation says 'unsupported'

https://github.com/boostorg/mpi/blob/develop/doc/c_mapping.qbk#L86-L89

Is this intended or not?

**Comment by aminiussi** [comment]
Thanks for reporting that. 

The "unsupported" is now a mistake. There is a test for that one. 

I'll fix it. 

Cheers

**Comment by aminiussi** [comment]
Done
