### ISSUE TITLE
MPI_Probe might have een fixed with Intel MPI 2019.4

### ISSUE THREAD

**Issue by aminiussi** [boostorg/mpi#95]
Meaning that #63 and #62 might behave correctly with that implementation

**Comment by aminiussi** [comment]
Merged on develop and master.
Tested on openmpi 2.1.1 and Intel MPI 2019.4

**Comment by mennodeij** [comment]
Today I found out that Intel MPI 2020.1 (to be exact: `icc (ICC) 19.1.1.217 20200306`) still has problems with MPI_IMProbe. If I remove any bits that `#define BOOST_MPI_USE_IMPROBE 1` from `boost/mpi/config.hpp` the problem we experienced with this goes away.

It was difficult to pinpoint but it looks like calls to `mpi::wait_all` did not get handled properly, but I can't be sure.
